//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Genies.UI.Widgets.PointerHandler2D.PointerValueChangedEvent))]
	public class PropertyProvider_Genies_UI_Widgets_PointerHandler2D_PointerValueChangedEvent : Unity.VisualScripting.SerializedPropertyProvider<Genies.UI.Widgets.PointerHandler2D.PointerValueChangedEvent>
	{
	}
}
